[package]
name = "subscan"
version = "0.1.0"
edition = "2021"
description = "Next generation subdomain enumeration tool"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.37.0", features = ["full"] }
clap = { version = "4.5.4", features = ["derive"] }
reqwest = "0.12.4"
scraper = "0.19.0"
regex = "1.10.4"
serde_json = "1.0.116"
