[package]
name = "subscan"
version = "0.1.0"
edition = "2021"
description = "Next generation subdomain enumeration tool"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.17", features = ["derive"] }
tokio = { version = "1.40.0", features = ["full"] }
headless_chrome = { version = "1.0.14", features = ["fetch"] }
reqwest = "0.12.7"
scraper = "0.20.0"
regex = "1.10.6"
serde_json = "1.0.128"
async-trait = "0.1.82"
lazy_static = "1.5.0"
enum_dispatch = "0.3.13"

[dev-dependencies]
automod = "1.0.14"
stubr = "0.6.2"
