[package]
name = "subscan"
version = "0.1.1"
edition = "2021"
description = "Next generation subdomain enumeration tool"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.19", features = ["derive"] }
tokio = { version = "1.40.0", features = ["full"] }
headless_chrome = { version = "1.0.15", features = ["fetch"] }
reqwest = "0.12.8"
scraper = "0.20.0"
regex = "1.11.0"
serde_json = "1.0.128"
async-trait = "0.1.83"
lazy_static = "1.5.0"
enum_dispatch = "0.3.13"
dotenvy = "0.15.7"

[dev-dependencies]
md5 = "0.7.0"
automod = "1.0.14"
stubr = "0.6.2"
