# Configuration for https://github.com/EmbarkStudios/cargo-deny

[licenses]
confidence-threshold = 0.8
allow = [
    "MIT",
    "Apache-2.0",
    "OpenSSL",
    "ISC",
    "BSD-3-Clause",
    "GPL-3.0",
    "BSL-1.0",
    "Unicode-DFS-2016",
    "Unicode-3.0",
    "MPL-2.0",
    "Zlib",
    "LGPL-3.0",
    "CDLA-Permissive-2.0",
]

[[licenses.clarify]]
crate = "ring"
expression = "MIT AND ISC AND OpenSSL"

license-files = [
    # Each entry is a crate relative path, and the (opaque) hash of its contents
    { path = "LICENSE", hash = 0xbd0eed23 }
]

[advisories]
# Add the unmaintained crate here
ignore = [
    { id = "RUSTSEC-2024-0384", reason = "Not maintained, but no upgrade option" },
    { id = "RUSTSEC-2025-0010", reason = "ring 0.16.20 was released over 4 years ago and isn't maintained" },
    { id = "RUSTSEC-2025-0009", reason = "ring::aead::quic::HeaderProtectionKey::new_mask() may panic when overflow checking is enabled" },
    { id = "RUSTSEC-2025-0014", reason = "Latest humantime crates.io release is four years old and GitHub repository has not seen commits in four years" },
]
