[book]
authors = ["Erdoğan Yoksul <erdoganyoksul3@gmail.com>"]
language = "en"
multilingual = false
src = "src"
title = "subscan"
description = "A subdomain enumeration tool leveraging diverse techniques, designed for advanced pentesting operations"

[rust]
edition = "2021"

[build]
create-missing = false

[output.html.search]
limit-results = 15

[output.html]
default-theme = "ayu"
git-repository-url = "https://github.com/eredotpkfr/subscan"
cname = "www.erdoganyoksul.com"

[preprocessor.index]

[preprocessor.links]
