name: Coverage

on:
  workflow_call:
  pull_request:
    branches: ["main"]

env:
  RUSTFLAGS: "-Dwarnings"
  CARGO_TERM_COLOR: "always"

jobs:
  cargo-llvm-cov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: llvm-tools-preview
      - uses: taiki-e/install-action@cargo-llvm-cov
      - uses: taiki-e/install-action@nextest
      - uses: Swatinem/rust-cache@v2

      - name: Clean workspace
        run: cargo llvm-cov clean --workspace

      - name: Run nextest
        run: cargo llvm-cov \
          --cargo-profile coverage \
          --all-features \
          --workspace \
          --no-report \
          nextest

      - name: Run doc-test
        run: cargo +nightly llvm-cov \
          --profile coverage \
          --all-features \
          --workspace \
          --no-report \
          --doc

      - name: Generate code coverage report
        run: cargo +nightly llvm-cov report \
          --doctests \
          --lcov \
          --output-path lcov.info

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: lcov.info
          fail_ci_if_error: true
