name: Coverage

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

env:
  RUSTFLAGS: "-Dwarnings"
  CARGO_TERM_COLOR: "always"

jobs:
  cargo-llvm-cov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - uses: taiki-e/install-action@cargo-llvm-cov
      - uses: Swatinem/rust-cache@v2

      - name: Add LLVM repository
        run: |
          sudo apt-get update
          sudo apt-get install -y gnupg curl
          curl -fsSL https://apt.llvm.org/llvm.sh | sudo bash

      - name: Install llvm-lld
        run: |
          sudo apt-get update
          sudo apt-get install llvm lld

      - name: Generate code coverage
        run: |
          cargo +nightly llvm-cov \
          --all-features \
          --workspace \
          --doctests \
          --lcov \
          --output-path lcov.info

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info
          fail_ci_if_error: true
