name: Github Pages

on:
  pull_request:
    branches: ["main"]
  push:
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+*'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: 'latest'

      - name: Run mdBook tests
        run: make book-test

  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: tests
    steps:
      - uses: actions/checkout@v4

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: 'latest'

      - name: Build mdBook
        run: make book-build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ startsWith(github.ref, 'refs/tags') }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: book/book
