name: Rust Cargo Test

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main", "dev" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Run tests
      run: cargo test --all-features

    - name: Run rustfmt
      run: cargo fmt --all -- --check

    - name: Run clippy
      run: cargo clippy --all --all-features --tests -- -D warnings
