name: Rust Cargo Test

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main", "dev" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Run rustfmt
      run: make rustfmt-check

    - name: Run clippy
      run: make clippy

    - name: Run tests
      run: make test
