name: Security

on:
  pull_request:
    branches: ["main", "dev"]

env:
  RUSTFLAGS: "-Dwarnings"
  CARGO_TERM_COLOR: "always"

jobs:
  rust-cargo-deny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: EmbarkStudios/cargo-deny-action@v2

  rust-cargo-machete:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: bnjbvr/cargo-machete@v0.6.2
