name: Rust Linters

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main", "dev" ]

env:
  RUSTFLAGS: "-Dwarnings"
  CARGO_TERM_COLOR: "always"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Run rustfmt
      run: make rustfmt-check

    - name: Run clippy
      run: make clippy
