name: Coverage

on:
  push:
    branches: ["*"]

env:
  RUSTFLAGS: "-Dwarnings"
  CARGO_TERM_COLOR: "always"

jobs:
  tarpaulin:
    runs-on: ubuntu-latest
    container:
        image: xd009642/tarpaulin:develop-nightly
        options: --security-opt seccomp=unconfined
    steps:
      - uses: actions/checkout@v4

      - name: Generate code coverage
        run: |
          cargo +nightly tarpaulin --all-features --workspace --timeout 120 --out xml

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v4
        with:
            fail_ci_if_error: true
