name: Tests

on:
  push:
    branches: ["**"]

  pull_request:
    branches: ["main", "dev"]

env:
  RUSTFLAGS: "-Dwarnings"
  CARGO_TERM_COLOR: "always"

jobs:
  rust-cargo-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        run: make test
