name: Tests

on:
  workflow_call:
  pull_request:
    branches: ["main"]

env:
  RUSTFLAGS: "-Dwarnings"
  CARGO_TERM_COLOR: "always"

jobs:
  rust-cargo-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@nextest

      - name: Run nextest
        run: sudo make nextest
        env:
          RUST_BACKTRACE: 1
      - name: Run doc-test
        run: make doc-test
